/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2012-03-18 06:49:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class budget_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fsubview_0026_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005ffor_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fselectOneMenu_0026_005fvalueChangeListener_005fvalue_005fonchange_005fid_005fforceId;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fselectItems_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdataTable_0026_005fvar_005fvalue_005frowClasses_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fcolumn;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fcolumn_0026_005fstyleClass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fsubview_0026_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005ffor_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fselectOneMenu_0026_005fvalueChangeListener_005fvalue_005fonchange_005fid_005fforceId = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005fselectItems_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdataTable_0026_005fvar_005fvalue_005frowClasses_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fcolumn = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fcolumn_0026_005fstyleClass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fsubview_0026_005fid.release();
    _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005ffor_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fselectOneMenu_0026_005fvalueChangeListener_005fvalue_005fonchange_005fid_005fforceId.release();
    _005fjspx_005ftagPool_005ff_005fselectItems_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdataTable_0026_005fvar_005fvalue_005frowClasses_005fid.release();
    _005fjspx_005ftagPool_005ft_005fcolumn.release();
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.release();
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fcolumn_0026_005fstyleClass.release();
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue.release();
    _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_f_005fsubview_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fsubview_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:subview
    org.apache.myfaces.taglib.core.SubviewTag _jspx_th_f_005fsubview_005f0 = (new org.apache.myfaces.taglib.core.SubviewTag());
    _jsp_instancemanager.newInstance(_jspx_th_f_005fsubview_005f0);
    _jspx_th_f_005fsubview_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005fsubview_005f0.setParent(null);
    // /pages/budget.jsp(4,0) name = id type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005fsubview_005f0.setId("budget");
    _jspx_th_f_005fsubview_005f0.setJspId("jsp_1518779290_0");
    int _jspx_eval_f_005fsubview_005f0 = _jspx_th_f_005fsubview_005f0.doStartTag();
    if (_jspx_eval_f_005fsubview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_f_005fsubview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_f_005fsubview_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_f_005fsubview_005f0.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t<h2>Monthly Budget</h2>\n");
        out.write("\t");
        if (_jspx_meth_h_005foutputLabel_005f0(_jspx_th_f_005fsubview_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        if (_jspx_meth_t_005fselectOneMenu_005f0(_jspx_th_f_005fsubview_005f0, _jspx_page_context))
          return true;
        out.write(' ');
        out.write('\n');
        out.write('	');
        if (_jspx_meth_t_005fdataTable_005f0(_jspx_th_f_005fsubview_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        int evalDoAfterBody = _jspx_th_f_005fsubview_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_f_005fsubview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_f_005fsubview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_f_005fsubview_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_f_005fsubview_005f0);
      return true;
    }
    _jspx_th_f_005fsubview_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_f_005fsubview_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005foutputLabel_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fsubview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputLabel
    org.apache.myfaces.taglib.html.HtmlOutputLabelTag _jspx_th_h_005foutputLabel_005f0 = (new org.apache.myfaces.taglib.html.HtmlOutputLabelTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputLabel_005f0);
    _jspx_th_h_005foutputLabel_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputLabel_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fsubview_005f0);
    // /pages/budget.jsp(6,1) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputLabel_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(6,1) 'Month:'",_el_expressionfactory.createValueExpression("Month:",java.lang.Object.class)));
    // /pages/budget.jsp(6,1) name = for type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputLabel_005f0.setFor(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(6,1) 'budgetMonth'",_el_expressionfactory.createValueExpression("budgetMonth",java.lang.Object.class)));
    _jspx_th_h_005foutputLabel_005f0.setJspId("jsp_1518779290_1");
    int _jspx_eval_h_005foutputLabel_005f0 = _jspx_th_h_005foutputLabel_005f0.doStartTag();
    if (_jspx_th_h_005foutputLabel_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputLabel_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputLabel_005f0);
      return true;
    }
    _jspx_th_h_005foutputLabel_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputLabel_005f0);
    return false;
  }

  private boolean _jspx_meth_t_005fselectOneMenu_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fsubview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:selectOneMenu
    org.apache.myfaces.generated.taglib.html.ext.HtmlSelectOneMenuTag _jspx_th_t_005fselectOneMenu_005f0 = (new org.apache.myfaces.generated.taglib.html.ext.HtmlSelectOneMenuTag());
    _jsp_instancemanager.newInstance(_jspx_th_t_005fselectOneMenu_005f0);
    _jspx_th_t_005fselectOneMenu_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fselectOneMenu_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fsubview_005f0);
    // /pages/budget.jsp(7,1) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fselectOneMenu_005f0.setId("budgetMonth");
    // /pages/budget.jsp(7,1) name = forceId type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fselectOneMenu_005f0.setForceId("true");
    // /pages/budget.jsp(7,1) name = onchange type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_t_005fselectOneMenu_005f0.setOnchange(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(7,1) 'submit()'",_el_expressionfactory.createValueExpression("submit()",java.lang.Object.class)));
    // /pages/budget.jsp(7,1) name = valueChangeListener type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = void myMethod( javax.faces.event.ValueChangeEvent )
    _jspx_th_t_005fselectOneMenu_005f0.setValueChangeListener(new org.apache.jasper.el.JspMethodExpression("/pages/budget.jsp(7,1) '#{budgetBackingBean.monthChanged}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{budgetBackingBean.monthChanged}",java.lang.Void.TYPE,new java.lang.Class[] {javax.faces.event.ValueChangeEvent.class})));
    // /pages/budget.jsp(7,1) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_t_005fselectOneMenu_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(7,1) '#{budgetBackingBean.budgetMonth}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{budgetBackingBean.budgetMonth}",java.lang.Object.class)));
    _jspx_th_t_005fselectOneMenu_005f0.setJspId("jsp_1518779290_2");
    int _jspx_eval_t_005fselectOneMenu_005f0 = _jspx_th_t_005fselectOneMenu_005f0.doStartTag();
    if (_jspx_eval_t_005fselectOneMenu_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_t_005fselectOneMenu_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_t_005fselectOneMenu_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_t_005fselectOneMenu_005f0.doInitBody();
      }
      do {
        out.write('\n');
        out.write('	');
        out.write('	');
        if (_jspx_meth_f_005fselectItems_005f0(_jspx_th_t_005fselectOneMenu_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_t_005fselectOneMenu_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_t_005fselectOneMenu_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_t_005fselectOneMenu_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_t_005fselectOneMenu_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_t_005fselectOneMenu_005f0);
      return true;
    }
    _jspx_th_t_005fselectOneMenu_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_t_005fselectOneMenu_005f0);
    return false;
  }

  private boolean _jspx_meth_f_005fselectItems_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fselectOneMenu_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:selectItems
    org.apache.myfaces.taglib.core.SelectItemsTag _jspx_th_f_005fselectItems_005f0 = (new org.apache.myfaces.taglib.core.SelectItemsTag());
    _jsp_instancemanager.newInstance(_jspx_th_f_005fselectItems_005f0);
    _jspx_th_f_005fselectItems_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005fselectItems_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fselectOneMenu_005f0);
    // /pages/budget.jsp(13,2) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_f_005fselectItems_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(13,2) '#{budgetBackingBean.availableBudgetMonths}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{budgetBackingBean.availableBudgetMonths}",java.lang.Object.class)));
    _jspx_th_f_005fselectItems_005f0.setJspId("jsp_1518779290_3");
    int _jspx_eval_f_005fselectItems_005f0 = _jspx_th_f_005fselectItems_005f0.doStartTag();
    if (_jspx_th_f_005fselectItems_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_f_005fselectItems_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_f_005fselectItems_005f0);
      return true;
    }
    _jspx_th_f_005fselectItems_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_f_005fselectItems_005f0);
    return false;
  }

  private boolean _jspx_meth_t_005fdataTable_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fsubview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dataTable
    org.apache.myfaces.generated.taglib.html.ext.HtmlDataTableTag _jspx_th_t_005fdataTable_005f0 = (new org.apache.myfaces.generated.taglib.html.ext.HtmlDataTableTag());
    _jsp_instancemanager.newInstance(_jspx_th_t_005fdataTable_005f0);
    _jspx_th_t_005fdataTable_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fdataTable_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fsubview_005f0);
    // /pages/budget.jsp(15,1) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fdataTable_005f0.setId("budgetItems");
    // /pages/budget.jsp(15,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fdataTable_005f0.setVar("results");
    // /pages/budget.jsp(15,1) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_t_005fdataTable_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(15,1) '#{budgetBackingBean.budgetItems}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{budgetBackingBean.budgetItems}",java.lang.Object.class)));
    // /pages/budget.jsp(15,1) name = rowClasses type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_t_005fdataTable_005f0.setRowClasses(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(15,1) 'odd, even'",_el_expressionfactory.createValueExpression("odd, even",java.lang.Object.class)));
    _jspx_th_t_005fdataTable_005f0.setJspId("jsp_1518779290_4");
    int _jspx_eval_t_005fdataTable_005f0 = _jspx_th_t_005fdataTable_005f0.doStartTag();
    if (_jspx_eval_t_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_t_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_t_005fdataTable_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_t_005fdataTable_005f0.doInitBody();
      }
      do {
        out.write('\n');
        out.write('	');
        out.write('	');
        if (_jspx_meth_t_005fcolumn_005f0(_jspx_th_t_005fdataTable_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        if (_jspx_meth_t_005fcolumn_005f1(_jspx_th_t_005fdataTable_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        if (_jspx_meth_t_005fcolumn_005f2(_jspx_th_t_005fdataTable_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        if (_jspx_meth_t_005fcolumn_005f3(_jspx_th_t_005fdataTable_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_t_005fdataTable_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_t_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_t_005fdataTable_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_t_005fdataTable_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_t_005fdataTable_005f0);
      return true;
    }
    _jspx_th_t_005fdataTable_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_t_005fdataTable_005f0);
    return false;
  }

  private boolean _jspx_meth_t_005fcolumn_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:column
    org.apache.myfaces.custom.column.HtmlColumnTag _jspx_th_t_005fcolumn_005f0 = (new org.apache.myfaces.custom.column.HtmlColumnTag());
    _jsp_instancemanager.newInstance(_jspx_th_t_005fcolumn_005f0);
    _jspx_th_t_005fcolumn_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fcolumn_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdataTable_005f0);
    _jspx_th_t_005fcolumn_005f0.setJspId("jsp_1518779290_5");
    int _jspx_eval_t_005fcolumn_005f0 = _jspx_th_t_005fcolumn_005f0.doStartTag();
    if (_jspx_eval_t_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_t_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_t_005fcolumn_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_t_005fcolumn_005f0.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t    ");
        if (_jspx_meth_f_005ffacet_005f0(_jspx_th_t_005fcolumn_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t \t");
        if (_jspx_meth_h_005foutputText_005f1(_jspx_th_t_005fcolumn_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t ");
        int evalDoAfterBody = _jspx_th_t_005fcolumn_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_t_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_t_005fcolumn_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_t_005fcolumn_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_t_005fcolumn_005f0);
      return true;
    }
    _jspx_th_t_005fcolumn_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_t_005fcolumn_005f0);
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fcolumn_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f0 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    _jspx_th_f_005ffacet_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005ffacet_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fcolumn_005f0);
    // /pages/budget.jsp(21,6) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005ffacet_005f0.setName("header");
    int _jspx_eval_f_005ffacet_005f0 = _jspx_th_f_005ffacet_005f0.doStartTag();
    if (_jspx_eval_f_005ffacet_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t    \t");
        if (_jspx_meth_h_005foutputText_005f0(_jspx_th_f_005ffacet_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t    ");
        int evalDoAfterBody = _jspx_th_f_005ffacet_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_f_005ffacet_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    org.apache.myfaces.taglib.html.HtmlOutputTextTag _jspx_th_h_005foutputText_005f0 = (new org.apache.myfaces.taglib.html.HtmlOutputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputText_005f0);
    _jspx_th_h_005foutputText_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputText_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f0);
    // /pages/budget.jsp(22,7) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(22,7) 'Category'",_el_expressionfactory.createValueExpression("Category",java.lang.Object.class)));
    _jspx_th_h_005foutputText_005f0.setJspId("jsp_1518779290_6");
    int _jspx_eval_h_005foutputText_005f0 = _jspx_th_h_005foutputText_005f0.doStartTag();
    if (_jspx_th_h_005foutputText_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputText_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f0);
      return true;
    }
    _jspx_th_h_005foutputText_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fcolumn_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    org.apache.myfaces.taglib.html.HtmlOutputTextTag _jspx_th_h_005foutputText_005f1 = (new org.apache.myfaces.taglib.html.HtmlOutputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputText_005f1);
    _jspx_th_h_005foutputText_005f1.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputText_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fcolumn_005f0);
    // /pages/budget.jsp(24,4) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(24,4) '#{results.budgetCategoryDescription}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{results.budgetCategoryDescription}",java.lang.Object.class)));
    _jspx_th_h_005foutputText_005f1.setJspId("jsp_1518779290_7");
    int _jspx_eval_h_005foutputText_005f1 = _jspx_th_h_005foutputText_005f1.doStartTag();
    if (_jspx_th_h_005foutputText_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputText_005f1.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f1);
      return true;
    }
    _jspx_th_h_005foutputText_005f1.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f1);
    return false;
  }

  private boolean _jspx_meth_t_005fcolumn_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:column
    org.apache.myfaces.custom.column.HtmlColumnTag _jspx_th_t_005fcolumn_005f1 = (new org.apache.myfaces.custom.column.HtmlColumnTag());
    _jsp_instancemanager.newInstance(_jspx_th_t_005fcolumn_005f1);
    _jspx_th_t_005fcolumn_005f1.setPageContext(_jspx_page_context);
    _jspx_th_t_005fcolumn_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdataTable_005f0);
    // /pages/budget.jsp(26,2) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_t_005fcolumn_005f1.setStyleClass(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(26,2) 'money'",_el_expressionfactory.createValueExpression("money",java.lang.Object.class)));
    _jspx_th_t_005fcolumn_005f1.setJspId("jsp_1518779290_8");
    int _jspx_eval_t_005fcolumn_005f1 = _jspx_th_t_005fcolumn_005f1.doStartTag();
    if (_jspx_eval_t_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_t_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_t_005fcolumn_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_t_005fcolumn_005f1.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t        ");
        if (_jspx_meth_f_005ffacet_005f1(_jspx_th_t_005fcolumn_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t        ");
        if (_jspx_meth_h_005foutputText_005f3(_jspx_th_t_005fcolumn_005f1, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        int evalDoAfterBody = _jspx_th_t_005fcolumn_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_t_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_t_005fcolumn_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_t_005fcolumn_005f1.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_t_005fcolumn_005f1);
      return true;
    }
    _jspx_th_t_005fcolumn_005f1.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_t_005fcolumn_005f1);
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fcolumn_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f1 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    _jspx_th_f_005ffacet_005f1.setPageContext(_jspx_page_context);
    _jspx_th_f_005ffacet_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fcolumn_005f1);
    // /pages/budget.jsp(27,9) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005ffacet_005f1.setName("header");
    int _jspx_eval_f_005ffacet_005f1 = _jspx_th_f_005ffacet_005f1.doStartTag();
    if (_jspx_eval_f_005ffacet_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t        \t");
        if (_jspx_meth_h_005foutputText_005f2(_jspx_th_f_005ffacet_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t        ");
        int evalDoAfterBody = _jspx_th_f_005ffacet_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_f_005ffacet_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f1);
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    org.apache.myfaces.taglib.html.HtmlOutputTextTag _jspx_th_h_005foutputText_005f2 = (new org.apache.myfaces.taglib.html.HtmlOutputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputText_005f2);
    _jspx_th_h_005foutputText_005f2.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputText_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f1);
    // /pages/budget.jsp(28,10) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(28,10) 'Budgeted'",_el_expressionfactory.createValueExpression("Budgeted",java.lang.Object.class)));
    _jspx_th_h_005foutputText_005f2.setJspId("jsp_1518779290_9");
    int _jspx_eval_h_005foutputText_005f2 = _jspx_th_h_005foutputText_005f2.doStartTag();
    if (_jspx_th_h_005foutputText_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputText_005f2.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f2);
      return true;
    }
    _jspx_th_h_005foutputText_005f2.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f2);
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fcolumn_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    org.apache.myfaces.taglib.html.HtmlOutputTextTag _jspx_th_h_005foutputText_005f3 = (new org.apache.myfaces.taglib.html.HtmlOutputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputText_005f3);
    _jspx_th_h_005foutputText_005f3.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputText_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fcolumn_005f1);
    // /pages/budget.jsp(30,9) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(30,9) '#{results.budgetAmount}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{results.budgetAmount}",java.lang.Object.class)));
    _jspx_th_h_005foutputText_005f3.setJspId("jsp_1518779290_10");
    int _jspx_eval_h_005foutputText_005f3 = _jspx_th_h_005foutputText_005f3.doStartTag();
    if (_jspx_eval_h_005foutputText_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005foutputText_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005foutputText_005f3.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005foutputText_005f3.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t        \t");
        if (_jspx_meth_f_005fconvertNumber_005f0(_jspx_th_h_005foutputText_005f3, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t        ");
        int evalDoAfterBody = _jspx_th_h_005foutputText_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005foutputText_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005foutputText_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputText_005f3.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f3);
      return true;
    }
    _jspx_th_h_005foutputText_005f3.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f3);
    return false;
  }

  private boolean _jspx_meth_f_005fconvertNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005foutputText_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:convertNumber
    org.apache.myfaces.taglib.core.ConvertNumberTag _jspx_th_f_005fconvertNumber_005f0 = (org.apache.myfaces.taglib.core.ConvertNumberTag) _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody.get(org.apache.myfaces.taglib.core.ConvertNumberTag.class);
    _jspx_th_f_005fconvertNumber_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005fconvertNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005foutputText_005f3);
    // /pages/budget.jsp(31,10) name = maxFractionDigits type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = int deferredMethod = false methodSignature = null
    _jspx_th_f_005fconvertNumber_005f0.setMaxFractionDigits(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(31,10) '2'",_el_expressionfactory.createValueExpression("2",int.class)));
    // /pages/budget.jsp(31,10) name = currencySymbol type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_f_005fconvertNumber_005f0.setCurrencySymbol(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(31,10) '$'",_el_expressionfactory.createValueExpression("$",java.lang.Object.class)));
    // /pages/budget.jsp(31,10) name = type type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_f_005fconvertNumber_005f0.setType(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(31,10) 'currency'",_el_expressionfactory.createValueExpression("currency",java.lang.Object.class)));
    int _jspx_eval_f_005fconvertNumber_005f0 = _jspx_th_f_005fconvertNumber_005f0.doStartTag();
    if (_jspx_th_f_005fconvertNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody.reuse(_jspx_th_f_005fconvertNumber_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody.reuse(_jspx_th_f_005fconvertNumber_005f0);
    return false;
  }

  private boolean _jspx_meth_t_005fcolumn_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:column
    org.apache.myfaces.custom.column.HtmlColumnTag _jspx_th_t_005fcolumn_005f2 = (new org.apache.myfaces.custom.column.HtmlColumnTag());
    _jsp_instancemanager.newInstance(_jspx_th_t_005fcolumn_005f2);
    _jspx_th_t_005fcolumn_005f2.setPageContext(_jspx_page_context);
    _jspx_th_t_005fcolumn_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdataTable_005f0);
    // /pages/budget.jsp(34,2) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_t_005fcolumn_005f2.setStyleClass(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(34,2) 'money'",_el_expressionfactory.createValueExpression("money",java.lang.Object.class)));
    _jspx_th_t_005fcolumn_005f2.setJspId("jsp_1518779290_11");
    int _jspx_eval_t_005fcolumn_005f2 = _jspx_th_t_005fcolumn_005f2.doStartTag();
    if (_jspx_eval_t_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_t_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_t_005fcolumn_005f2.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_t_005fcolumn_005f2.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t        ");
        if (_jspx_meth_f_005ffacet_005f2(_jspx_th_t_005fcolumn_005f2, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t        ");
        if (_jspx_meth_h_005foutputText_005f5(_jspx_th_t_005fcolumn_005f2, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        int evalDoAfterBody = _jspx_th_t_005fcolumn_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_t_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_t_005fcolumn_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_t_005fcolumn_005f2.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_t_005fcolumn_005f2);
      return true;
    }
    _jspx_th_t_005fcolumn_005f2.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_t_005fcolumn_005f2);
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fcolumn_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f2 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    _jspx_th_f_005ffacet_005f2.setPageContext(_jspx_page_context);
    _jspx_th_f_005ffacet_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fcolumn_005f2);
    // /pages/budget.jsp(35,9) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005ffacet_005f2.setName("header");
    int _jspx_eval_f_005ffacet_005f2 = _jspx_th_f_005ffacet_005f2.doStartTag();
    if (_jspx_eval_f_005ffacet_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t        \t");
        if (_jspx_meth_h_005foutputText_005f4(_jspx_th_f_005ffacet_005f2, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t        ");
        int evalDoAfterBody = _jspx_th_f_005ffacet_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_f_005ffacet_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f2);
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    org.apache.myfaces.taglib.html.HtmlOutputTextTag _jspx_th_h_005foutputText_005f4 = (new org.apache.myfaces.taglib.html.HtmlOutputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputText_005f4);
    _jspx_th_h_005foutputText_005f4.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputText_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f2);
    // /pages/budget.jsp(36,10) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(36,10) 'Spent'",_el_expressionfactory.createValueExpression("Spent",java.lang.Object.class)));
    _jspx_th_h_005foutputText_005f4.setJspId("jsp_1518779290_12");
    int _jspx_eval_h_005foutputText_005f4 = _jspx_th_h_005foutputText_005f4.doStartTag();
    if (_jspx_th_h_005foutputText_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputText_005f4.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f4);
      return true;
    }
    _jspx_th_h_005foutputText_005f4.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f4);
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fcolumn_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    org.apache.myfaces.taglib.html.HtmlOutputTextTag _jspx_th_h_005foutputText_005f5 = (new org.apache.myfaces.taglib.html.HtmlOutputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputText_005f5);
    _jspx_th_h_005foutputText_005f5.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputText_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fcolumn_005f2);
    // /pages/budget.jsp(38,9) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f5.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(38,9) '#{results.totalSpentAmount}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{results.totalSpentAmount}",java.lang.Object.class)));
    _jspx_th_h_005foutputText_005f5.setJspId("jsp_1518779290_13");
    int _jspx_eval_h_005foutputText_005f5 = _jspx_th_h_005foutputText_005f5.doStartTag();
    if (_jspx_eval_h_005foutputText_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005foutputText_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005foutputText_005f5.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005foutputText_005f5.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t        \t");
        if (_jspx_meth_f_005fconvertNumber_005f1(_jspx_th_h_005foutputText_005f5, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t        ");
        int evalDoAfterBody = _jspx_th_h_005foutputText_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005foutputText_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005foutputText_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputText_005f5.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f5);
      return true;
    }
    _jspx_th_h_005foutputText_005f5.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f5);
    return false;
  }

  private boolean _jspx_meth_f_005fconvertNumber_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005foutputText_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:convertNumber
    org.apache.myfaces.taglib.core.ConvertNumberTag _jspx_th_f_005fconvertNumber_005f1 = (org.apache.myfaces.taglib.core.ConvertNumberTag) _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody.get(org.apache.myfaces.taglib.core.ConvertNumberTag.class);
    _jspx_th_f_005fconvertNumber_005f1.setPageContext(_jspx_page_context);
    _jspx_th_f_005fconvertNumber_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005foutputText_005f5);
    // /pages/budget.jsp(39,10) name = maxFractionDigits type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = int deferredMethod = false methodSignature = null
    _jspx_th_f_005fconvertNumber_005f1.setMaxFractionDigits(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(39,10) '2'",_el_expressionfactory.createValueExpression("2",int.class)));
    // /pages/budget.jsp(39,10) name = currencySymbol type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_f_005fconvertNumber_005f1.setCurrencySymbol(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(39,10) '$'",_el_expressionfactory.createValueExpression("$",java.lang.Object.class)));
    // /pages/budget.jsp(39,10) name = type type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_f_005fconvertNumber_005f1.setType(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(39,10) 'currency'",_el_expressionfactory.createValueExpression("currency",java.lang.Object.class)));
    int _jspx_eval_f_005fconvertNumber_005f1 = _jspx_th_f_005fconvertNumber_005f1.doStartTag();
    if (_jspx_th_f_005fconvertNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody.reuse(_jspx_th_f_005fconvertNumber_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody.reuse(_jspx_th_f_005fconvertNumber_005f1);
    return false;
  }

  private boolean _jspx_meth_t_005fcolumn_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:column
    org.apache.myfaces.custom.column.HtmlColumnTag _jspx_th_t_005fcolumn_005f3 = (new org.apache.myfaces.custom.column.HtmlColumnTag());
    _jsp_instancemanager.newInstance(_jspx_th_t_005fcolumn_005f3);
    _jspx_th_t_005fcolumn_005f3.setPageContext(_jspx_page_context);
    _jspx_th_t_005fcolumn_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdataTable_005f0);
    // /pages/budget.jsp(42,2) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_t_005fcolumn_005f3.setStyleClass(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(42,2) 'money'",_el_expressionfactory.createValueExpression("money",java.lang.Object.class)));
    _jspx_th_t_005fcolumn_005f3.setJspId("jsp_1518779290_14");
    int _jspx_eval_t_005fcolumn_005f3 = _jspx_th_t_005fcolumn_005f3.doStartTag();
    if (_jspx_eval_t_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_t_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_t_005fcolumn_005f3.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_t_005fcolumn_005f3.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t        ");
        if (_jspx_meth_f_005ffacet_005f3(_jspx_th_t_005fcolumn_005f3, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t        ");
        if (_jspx_meth_h_005foutputText_005f7(_jspx_th_t_005fcolumn_005f3, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        int evalDoAfterBody = _jspx_th_t_005fcolumn_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_t_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_t_005fcolumn_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_t_005fcolumn_005f3.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_t_005fcolumn_005f3);
      return true;
    }
    _jspx_th_t_005fcolumn_005f3.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_t_005fcolumn_005f3);
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fcolumn_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f3 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    _jspx_th_f_005ffacet_005f3.setPageContext(_jspx_page_context);
    _jspx_th_f_005ffacet_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fcolumn_005f3);
    // /pages/budget.jsp(43,9) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_f_005ffacet_005f3.setName("header");
    int _jspx_eval_f_005ffacet_005f3 = _jspx_th_f_005ffacet_005f3.doStartTag();
    if (_jspx_eval_f_005ffacet_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t        \t");
        if (_jspx_meth_h_005foutputText_005f6(_jspx_th_f_005ffacet_005f3, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t        ");
        int evalDoAfterBody = _jspx_th_f_005ffacet_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_f_005ffacet_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f3);
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    org.apache.myfaces.taglib.html.HtmlOutputTextTag _jspx_th_h_005foutputText_005f6 = (new org.apache.myfaces.taglib.html.HtmlOutputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputText_005f6);
    _jspx_th_h_005foutputText_005f6.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputText_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f3);
    // /pages/budget.jsp(44,10) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f6.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(44,10) 'Remaining'",_el_expressionfactory.createValueExpression("Remaining",java.lang.Object.class)));
    _jspx_th_h_005foutputText_005f6.setJspId("jsp_1518779290_15");
    int _jspx_eval_h_005foutputText_005f6 = _jspx_th_h_005foutputText_005f6.doStartTag();
    if (_jspx_th_h_005foutputText_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputText_005f6.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f6);
      return true;
    }
    _jspx_th_h_005foutputText_005f6.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f6);
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fcolumn_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    org.apache.myfaces.taglib.html.HtmlOutputTextTag _jspx_th_h_005foutputText_005f7 = (new org.apache.myfaces.taglib.html.HtmlOutputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005foutputText_005f7);
    _jspx_th_h_005foutputText_005f7.setPageContext(_jspx_page_context);
    _jspx_th_h_005foutputText_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fcolumn_005f3);
    // /pages/budget.jsp(46,9) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005foutputText_005f7.setValue(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(46,9) '#{results.budgetAmount - results.totalSpentAmount}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{results.budgetAmount - results.totalSpentAmount}",java.lang.Object.class)));
    _jspx_th_h_005foutputText_005f7.setJspId("jsp_1518779290_16");
    int _jspx_eval_h_005foutputText_005f7 = _jspx_th_h_005foutputText_005f7.doStartTag();
    if (_jspx_eval_h_005foutputText_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005foutputText_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005foutputText_005f7.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005foutputText_005f7.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t        \t");
        if (_jspx_meth_f_005fconvertNumber_005f2(_jspx_th_h_005foutputText_005f7, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t        ");
        int evalDoAfterBody = _jspx_th_h_005foutputText_005f7.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005foutputText_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005foutputText_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005foutputText_005f7.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f7);
      return true;
    }
    _jspx_th_h_005foutputText_005f7.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005foutputText_005f7);
    return false;
  }

  private boolean _jspx_meth_f_005fconvertNumber_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005foutputText_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:convertNumber
    org.apache.myfaces.taglib.core.ConvertNumberTag _jspx_th_f_005fconvertNumber_005f2 = (org.apache.myfaces.taglib.core.ConvertNumberTag) _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody.get(org.apache.myfaces.taglib.core.ConvertNumberTag.class);
    _jspx_th_f_005fconvertNumber_005f2.setPageContext(_jspx_page_context);
    _jspx_th_f_005fconvertNumber_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005foutputText_005f7);
    // /pages/budget.jsp(47,10) name = maxFractionDigits type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = int deferredMethod = false methodSignature = null
    _jspx_th_f_005fconvertNumber_005f2.setMaxFractionDigits(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(47,10) '2'",_el_expressionfactory.createValueExpression("2",int.class)));
    // /pages/budget.jsp(47,10) name = currencySymbol type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_f_005fconvertNumber_005f2.setCurrencySymbol(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(47,10) '$'",_el_expressionfactory.createValueExpression("$",java.lang.Object.class)));
    // /pages/budget.jsp(47,10) name = type type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_f_005fconvertNumber_005f2.setType(new org.apache.jasper.el.JspValueExpression("/pages/budget.jsp(47,10) 'currency'",_el_expressionfactory.createValueExpression("currency",java.lang.Object.class)));
    int _jspx_eval_f_005fconvertNumber_005f2 = _jspx_th_f_005fconvertNumber_005f2.doStartTag();
    if (_jspx_th_f_005fconvertNumber_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody.reuse(_jspx_th_f_005fconvertNumber_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ff_005fconvertNumber_0026_005ftype_005fmaxFractionDigits_005fcurrencySymbol_005fnobody.reuse(_jspx_th_f_005fconvertNumber_005f2);
    return false;
  }
}
