/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2012-03-18 22:29:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fview;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fform_0026_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fmessages_0026_005finfoClass_005fid_005fforceId_005ferrorClass_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fview = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fform_0026_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fmessages_0026_005finfoClass_005fid_005fforceId_005ferrorClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fview.release();
    _005fjspx_005ftagPool_005fh_005fform_0026_005fid.release();
    _005fjspx_005ftagPool_005ft_005fmessages_0026_005finfoClass_005fid_005fforceId_005ferrorClass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_f_005fview_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fview_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  f:view
    org.apache.myfaces.taglib.core.ViewTag _jspx_th_f_005fview_005f0 = (new org.apache.myfaces.taglib.core.ViewTag());
    _jsp_instancemanager.newInstance(_jspx_th_f_005fview_005f0);
    _jspx_th_f_005fview_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005fview_005f0.setParent(null);
    _jspx_th_f_005fview_005f0.setJspId("jsp_909133023_0");
    int _jspx_eval_f_005fview_005f0 = _jspx_th_f_005fview_005f0.doStartTag();
    if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_f_005fview_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_f_005fview_005f0.doInitBody();
      }
      do {
        out.write("\n");
        out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.1 Strict//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n");
        out.write("<html>\n");
        out.write("\t<head>\n");
        out.write("\t\t<title>Welcome to Expense Tracker</title>\n");
        out.write("\t\t<link rel=\"stylesheet\" href=\"../css/main.css\" type=\"text/css\" />\n");
        out.write("\t\t<link rel=\"stylesheet\" href=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/base/jquery-ui.css\" type=\"text/css\" />\n");
        out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\" type=\"text/javascript\"></script>\n");
        out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js\" type=\"text/javascript\"></script>\n");
        out.write("\t\t<script type=\"application/javascript\">\n");
        out.write("\t\t\t$(function (){ \n");
        out.write("\t\t\t\t$(\"#expenseDate\").datepicker();\n");
        out.write("\t\t\t});\n");
        out.write("\t\t</script>\n");
        out.write("\t</head>\n");
        out.write("\t<body>\n");
        out.write("\t\t");
        if (_jspx_meth_h_005fform_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t</body>\n");
        out.write("</html>\n");
        int evalDoAfterBody = _jspx_th_f_005fview_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_f_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_f_005fview_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_f_005fview_005f0);
      return true;
    }
    _jspx_th_f_005fview_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_f_005fview_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f0 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f0);
    _jspx_th_h_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /pages/index.jsp(21,2) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_h_005fform_005f0.setId("expsenseTracker");
    _jspx_th_h_005fform_005f0.setJspId("jsp_909133023_1");
    int _jspx_eval_h_005fform_005f0 = _jspx_th_h_005fform_005f0.doStartTag();
    if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f0.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t\t<div id=\"header\">\n");
        out.write("\t\t\t\t<h1>Expense Tracker!</h1>\n");
        out.write("\t\t\t\t<p> \n");
        out.write("\t\t\t\t\tStay within your budget!  \n");
        out.write("\t\t\t\t\tEnter your receipts below and track how you're doing.\n");
        out.write("\t\t\t\t</p> \n");
        out.write("\t\t\t\t");
        if (_jspx_meth_t_005fmessages_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t</div>\n");
        out.write("\t\t\t<ul id=\"sections\">\n");
        out.write("\t\t\t\t<li id='enterExpense'>");
        org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "enterExpense.jsp", out, false);
        out.write("</li>\n");
        out.write("\t\t\t\t<li id='recentExpense'>");
        org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "recentExpenses.jsp", out, false);
        out.write("</li>\n");
        out.write("\t\t\t\t<li id='budget'>");
        org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "budget.jsp", out, false);
        out.write("</li>\n");
        out.write("\t\t\t</ul>\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_h_005fform_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f0);
      return true;
    }
    _jspx_th_h_005fform_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f0);
    return false;
  }

  private boolean _jspx_meth_t_005fmessages_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:messages
    org.apache.myfaces.generated.taglib.html.ext.HtmlMessagesTag _jspx_th_t_005fmessages_005f0 = (new org.apache.myfaces.generated.taglib.html.ext.HtmlMessagesTag());
    _jsp_instancemanager.newInstance(_jspx_th_t_005fmessages_005f0);
    _jspx_th_t_005fmessages_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fmessages_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /pages/index.jsp(28,4) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmessages_005f0.setId("messages");
    // /pages/index.jsp(28,4) name = forceId type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fmessages_005f0.setForceId("true");
    // /pages/index.jsp(28,4) name = infoClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_t_005fmessages_005f0.setInfoClass(new org.apache.jasper.el.JspValueExpression("/pages/index.jsp(28,4) 'info'",_el_expressionfactory.createValueExpression("info",java.lang.Object.class)));
    // /pages/index.jsp(28,4) name = errorClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_t_005fmessages_005f0.setErrorClass(new org.apache.jasper.el.JspValueExpression("/pages/index.jsp(28,4) 'error'",_el_expressionfactory.createValueExpression("error",java.lang.Object.class)));
    _jspx_th_t_005fmessages_005f0.setJspId("jsp_909133023_2");
    int _jspx_eval_t_005fmessages_005f0 = _jspx_th_t_005fmessages_005f0.doStartTag();
    if (_jspx_th_t_005fmessages_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_t_005fmessages_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_t_005fmessages_005f0);
      return true;
    }
    _jspx_th_t_005fmessages_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_t_005fmessages_005f0);
    return false;
  }
}
